export const seoCategoryContent = {
  spa: {
    pathname: "/spa-randevu",
    title: "Spa Randevusu Al | Online Spa ve Masaj Randevu",
    description: "Spa merkezlerini keşfedin; masaj, hamam, sauna ve bakım hizmetleri için uygun günü ve saati seçerek online spa randevunuzu alın.",
    eyebrow: "Rahatlama ve yenilenme",
    category: "spa",
    benefits: ["Spa merkezlerinin hizmetlerini, sürelerini ve müsait saatlerini karşılaştırın.", "Masaj, hamam, sauna veya bakım deneyiminiz için uygun çalışanı seçin.", "Telefon trafiği olmadan randevunuzu hızlı ve güvenli şekilde oluşturun."],
    steps: ["Konumunuza göre spa merkezlerini ve hizmetlerini keşfedin.", "İstediğiniz masaj, bakım veya wellness hizmetini seçin.", "Müsait gün ve saati belirleyerek spa randevunuzu onaylayın."],
    faq: [{ question: "Spa randevusu online alınabilir mi?", answer: "Evet. Spa kategorisindeki işletmeleri ve hizmetleri inceleyerek müsait bir gün ve saatten online randevu alabilirsiniz." }, { question: "Spa randevusunda hangi hizmetler bulunur?", answer: "İşletmeye göre masaj, hamam, sauna, cilt bakımı, kese ve farklı wellness hizmetleri bulunabilir." }, { question: "Spa merkezini nasıl seçebilirim?", answer: "Hizmet detaylarını, süreleri, çalışma saatlerini ve müşteri yorumlarını karşılaştırarak size uygun spa merkezini seçebilirsiniz." }],
    relatedLinks: [{ href: "/kesfet?category=spa", label: "Spa merkezlerini keşfet" }, { href: "/online-randevu", label: "Online randevu" }, { href: "/guzellik-merkezi-randevu", label: "Güzellik randevusu" }],
  },
  saglik: {
    pathname: "/saglik-randevu",
    title: "Sağlık Randevusu Al | Online Sağlık Randevu Sistemi",
    description: "Sağlık hizmeti sunan işletmeleri keşfedin, uygun hizmet ve çalışma saatlerini inceleyerek online sağlık randevunuzu oluşturun.",
    eyebrow: "Sağlığınız için kolay erişim",
    category: "saglik",
    benefits: ["Sağlık hizmeti sunan işletmeleri şehir ve hizmete göre keşfedin.", "Uygun çalışma saatlerini inceleyerek planınıza göre randevu oluşturun.", "Randevu bilgilerinizi hesabınızdan düzenli şekilde takip edin."],
    steps: ["İhtiyacınıza ve konumunuza göre sağlık işletmelerini arayın.", "Sunulan hizmeti ve uygun çalışma saatini inceleyin.", "Bilgilerinizi girerek randevunuzu onaylayın ve işletmenin yönlendirmelerini takip edin."],
    faq: [{ question: "Online sağlık randevusu nasıl alınır?", answer: "Sağlık kategorisinden işletmeyi ve hizmeti seçip uygun bir gün ve saat belirleyerek online randevu oluşturabilirsiniz." }, { question: "Hangi sağlık hizmetlerini bulabilirim?", answer: "Platformdaki işletmelere göre danışmanlık, terapi, fizyoterapi, diyetisyen ve farklı sağlık hizmetleri bulunabilir." }, { question: "Randevu öncesi işletmeyi aramalı mıyım?", answer: "Hizmete göre değişebilir. İşletme profilindeki açıklamaları ve randevu sonrası yönlendirmeleri takip etmeniz yeterlidir." }],
    relatedLinks: [{ href: "/kesfet?category=saglik", label: "Sağlık işletmelerini keşfet" }, { href: "/online-randevu", label: "Online randevu" }, { href: "/danismanlik-randevu", label: "Danışmanlık randevusu" }],
  },
  spor: {
    pathname: "/spor-randevu",
    title: "Spor ve Fitness Randevusu Al | Online Spor Randevu",
    description: "Spor salonu, fitness stüdyosu ve kişisel antrenörleri keşfedin. Size uygun antrenman ve saat için online randevu alın.",
    eyebrow: "Harekete geçin",
    category: "spor",
    benefits: ["Spor salonlarını, stüdyoları ve kişisel antrenörleri tek yerde inceleyin.", "Antrenman türünü, çalışanı ve size uygun saati kendiniz seçin.", "Düzenli randevu planınızı kolayca oluşturup takip edin."],
    steps: ["Şehrinizdeki spor işletmelerini ve antrenman seçeneklerini keşfedin.", "Fitness, pilates, yoga veya kişisel antrenman hizmetini seçin.", "Uygun gün ve saati seçerek antrenman randevunuzu onaylayın."],
    faq: [{ question: "Spor salonu randevusu online alınır mı?", answer: "Evet. Spor kategorisindeki işletmelerden antrenman veya danışmanlık hizmeti için online randevu alabilirsiniz." }, { question: "Kişisel antrenör seçebilir miyim?", answer: "İşletme çalışanlarını ve hizmetlerini tanımladıysa size uygun kişisel antrenörü seçebilirsiniz." }, { question: "Hangi spor hizmetleri bulunur?", answer: "İşletmeye göre fitness, pilates, yoga, kişisel antrenman, dövüş sporları ve benzeri hizmetleri bulabilirsiniz." }],
    relatedLinks: [{ href: "/kesfet?category=spor", label: "Spor işletmelerini keşfet" }, { href: "/online-randevu", label: "Online randevu" }, { href: "/saglik-randevu", label: "Sağlık randevusu" }],
  },
  veteriner: {
    pathname: "/veteriner-randevu",
    title: "Veteriner Randevusu Al | Online Veteriner Randevu",
    description: "Evcil hayvanınız için veteriner kliniklerini keşfedin, sunulan hizmetleri inceleyin ve uygun zamanda online veteriner randevusu alın.",
    eyebrow: "Dostlarınız için özenli bakım",
    category: "veteriner",
    benefits: ["Veteriner kliniklerini konum, hizmet ve çalışma saatlerine göre karşılaştırın.", "Muayene, bakım ve kontrol hizmetleri için uygun zamanı seçin.", "Evcil hayvanınızın randevusunu düzenli ve hızlı şekilde planlayın."],
    steps: ["Yakınınızdaki veteriner kliniklerini keşfedin.", "Muayene veya ihtiyaç duyduğunuz hizmeti seçin.", "Uygun gün ve saati belirleyerek randevuyu tamamlayın."],
    faq: [{ question: "Veteriner randevusu online alınır mı?", answer: "Evet. Platformdaki veteriner işletmelerinden müsait gün ve saat seçerek online randevu oluşturabilirsiniz." }, { question: "Hangi veteriner hizmetlerini bulabilirim?", answer: "İşletmeye göre muayene, aşı, bakım, tımar ve farklı hayvan sağlığı hizmetleri bulunabilir." }, { question: "Acil durumlarda online randevu kullanmalı mıyım?", answer: "Acil durumlarda doğrudan veteriner kliniğiyle iletişime geçin; online randevu planlı ziyaretler içindir." }],
    relatedLinks: [{ href: "/kesfet?category=veteriner", label: "Veterinerleri keşfet" }, { href: "/online-randevu", label: "Online randevu" }, { href: "/saglik-randevu", label: "Sağlık randevusu" }],
  },
  nail: {
    pathname: "/nail-studio-randevu",
    title: "Nail Studio Randevusu Al | Online Manikür ve Nail Art Randevu",
    description: "Nail studio ve tırnak bakım işletmelerini keşfedin. Manikür, pedikür ve nail art hizmetleri için uygun saati online seçin.",
    eyebrow: "Detaylarda güzellik",
    category: "nail",
    benefits: ["Nail studio hizmetlerini ve çalışan seçeneklerini önceden inceleyin.", "Manikür, pedikür ve nail art için istediğiniz hizmeti seçin.", "Yoğun programınıza uygun saati saniyeler içinde ayırtın."],
    steps: ["Yakınınızdaki nail studio işletmelerini keşfedin.", "Manikür, pedikür, kalıcı oje veya nail art hizmetini seçin.", "Müsait zamanı onaylayarak bakım randevunuzu oluşturun."],
    faq: [{ question: "Nail studio randevusu nasıl alınır?", answer: "Nail kategorisindeki işletmeyi ve hizmeti seçin, ardından müsait gün ve saatlerden birini onaylayın." }, { question: "Nail art hizmeti bulabilir miyim?", answer: "İşletmenin hizmet listesine göre nail art, manikür, pedikür ve kalıcı oje seçeneklerini bulabilirsiniz." }, { question: "Randevu saatimi kendim seçebilir miyim?", answer: "Evet, işletmenin uygunluk durumuna göre size uygun saatlerden birini seçebilirsiniz." }],
    relatedLinks: [{ href: "/kesfet?category=nail", label: "Nail studio keşfet" }, { href: "/guzellik-merkezi-randevu", label: "Güzellik randevusu" }, { href: "/online-randevu", label: "Online randevu" }],
  },
  danismanlik: {
    pathname: "/danismanlik-randevu",
    title: "Danışmanlık Randevusu Al | Online Danışmanlık Randevu",
    description: "Danışmanlık hizmeti sunan uzmanları keşfedin, hizmet detaylarını inceleyin ve size uygun zaman için online randevu oluşturun.",
    eyebrow: "Uzman desteğine kolay erişim",
    category: "danismanlik",
    benefits: ["Danışmanlık hizmetlerini ve uzman profillerini tek yerde inceleyin.", "İhtiyacınıza uygun hizmeti ve görüşme zamanını seçin.", "Randevu planınızı hesabınızdan düzenli şekilde takip edin."],
    steps: ["Danışmanlık kategorisindeki uzmanları ve işletmeleri keşfedin.", "İhtiyacınıza uygun hizmeti ve uzmanı belirleyin.", "Müsait gün ve saati seçerek görüşme randevunuzu onaylayın."],
    faq: [{ question: "Danışmanlık randevusu online alınır mı?", answer: "Evet. Danışmanlık hizmeti sunan işletmelerden uygun gün ve saat seçerek online randevu alabilirsiniz." }, { question: "Hangi danışmanlık hizmetlerini bulabilirim?", answer: "İşletmeye göre kariyer, eğitim, yaşam, finans, işletme ve farklı uzmanlık alanlarında hizmetler bulunabilir." }, { question: "Randevu öncesi uzmanı inceleyebilir miyim?", answer: "İşletme profili ve hizmet detayları yayınlanmışsa randevu öncesinde bunları inceleyebilirsiniz." }],
    relatedLinks: [{ href: "/kesfet?category=danismanlik", label: "Danışmanları keşfet" }, { href: "/online-randevu", label: "Online randevu" }, { href: "/saglik-randevu", label: "Sağlık randevusu" }],
  },
} as const;
