import type { Metadata } from "next"; import { ContentPage } from "@/components/marketing/content-page";
export const metadata:Metadata={title:"Çerez Politikası",description:"SeninRandevun çerez kullanımı ve tercihleri.",alternates:{canonical:"/cerez-politikasi"}};
export default function Page(){return <ContentPage eyebrow="YASAL · 29 EYLÜL 2026" title="Çerez politikası" intro="Hangi çerezlerin neden kullanıldığını, ne zaman çalıştığını ve tercihini nasıl değiştirebileceğini açıklar. Zorunlu olmayan çerezler varsayılan olarak kapalıdır." sections={[
{title:"Çerez nedir?",body:"Çerezler ve benzer yerel depolama teknolojileri, tarayıcının hizmeti güvenli ve tutarlı biçimde çalıştırması veya izin verdiğiniz ölçüm ve pazarlama işlemlerini yapması için cihazda küçük bilgiler saklar."},
{title:"Zorunlu çerezler",body:"Güvenli oturum, kimlik doğrulama, dolandırıcılığın önlenmesi, dil veya tema, çerez tercihi ve temel form işlevleri için gereklidir. Bu kategori hizmetin çalışması için kullanılır ve tercih panelinden kapatılamaz."},
{title:"Analitik çerezler",body:"İzin verirseniz sayfa görüntüleme, etkileşim, cihaz türü ve performans gibi toplu verileri ölçer. Google Analytics ve Google Tag Manager yalnızca analitik tercihi açıkken yüklenir. Bu kategoriyi reddetmek temel hizmeti etkilemez."},
{title:"Pazarlama çerezleri",body:"İzin verirseniz kampanya performansını ölçmek ve ilgili içerik sunmak için kullanılabilir. Meta Pixel gibi pazarlama araçları yalnızca pazarlama tercihi açıkken yüklenir. Bu kategoriyi reddetmek randevu ve hesap işlevlerini etkilemez."},
{title:"Tercih ve kayıt",body:"İlk ziyarette Tümünü reddet, Tercihleri yönet ve Tümünü kabul et seçenekleri eşit biçimde sunulur. Seçimin kategori, sürüm ve tarih bilgisiyle cihazda saklanır; onay vermemek hizmete erişimi engellemez."},
{title:"Tercihi değiştirme",body:"Sayfa altındaki Çerez tercihleri bağlantısıyla paneli yeniden açabilir, analitik ve pazarlama kategorilerini bağımsız olarak değiştirebilirsiniz. Tarayıcı ayarlarıyla çerezleri silebilir veya engelleyebilirsiniz; zorunlu teknolojilerin engellenmesi bazı işlevleri bozabilir."},
{title:"Üçüncü taraflar ve süre",body:"Etkinleştirdiğiniz araçların çerez isimleri ve saklama süreleri sağlayıcının yapılandırmasına göre değişebilir. Yapılandırma değiştiğinde bu politika ve tercih sürümü gözden geçirilir. Sağlayıcılar kendi gizlilik metinlerine tabi olabilir."},
{title:"İletişim",body:"Çerezler ve tercih kaydınızla ilgili sorularınızı info@seninrandevun.com adresine iletebilirsiniz."}
]} cta={false}/>}
