import Link from "next/link";
import { ArrowRight, BarChart3, BellRing, CalendarDays, Check, Clock3, MessageSquareText, ShieldCheck, Smartphone, Store, UsersRound, WandSparkles } from "lucide-react";
import { BusinessPage } from "@/components/marketing/business-shell";
export const metadata={title:"İşletme Özellikleri",description:"Akıllı takvim, müşteri CRM, ekip, dijital mağaza ve analitik özelliklerini keşfedin.",alternates:{canonical:"/ozellikler"}};
const features=[
  {no:"01",icon:CalendarDays,title:"Akıllı takvim",lead:"Her dakikayı görünür, her randevuyu yönetilebilir kılın.",text:"Günlük, haftalık ve aylık görünümler; çalışan bazlı müsaitlik, mola, izin ve hizmet süreleriyle gerçek zamanlı çalışır.",items:["Çakışma engelleme","Sürükle-bırak planlama","Durum ve ödeme takibi","Çalışan filtreleri"]},
  {no:"02",icon:Store,title:"Dijital mağaza",lead:"İşletmeniz kapalıyken bile randevu almaya devam edin.",text:"Markanıza özel mobil mağaza; hizmetlerinizi, fiyatlarınızı, ekibinizi, yorumları ve canlı saatleri tek bağlantıda sunar.",items:["7/24 self-servis randevu","Keşfet görünürlüğü","Paylaşılabilir mağaza linki","Mobil öncelikli deneyim"]},
  {no:"03",icon:UsersRound,title:"Müşteri CRM",lead:"Her ziyaretle daha iyi hizmet veren bir müşteri hafızası.",text:"Ziyaret geçmişi, tercihler, notlar, iletişim ve harcama davranışını anlaşılır müşteri profillerinde birleştirin.",items:["Otomatik müşteri profili","Geçmiş ve gelecek randevular","Özel müşteri notları","Sadakat altyapısı"]},
  {no:"04",icon:BarChart3,title:"Büyüme analitiği",lead:"Verileri yalnızca izlemeyin; bir sonraki doğru adımı görün.",text:"Gelir, doluluk, iptal, hizmet ve ekip performansını canlı kartlar ve anlaşılır trendlerle takip edin.",items:["Canlı KPI kartları","Haftalık doluluk","Popüler hizmetler","Akıllı öneriler"]},
  {no:"05",icon:BellRing,title:"Otomatik iletişim",lead:"Hatırlatmaları sistem yapsın, ekibiniz müşteriye odaklansın.",text:"Teyit, değişiklik ve hatırlatma akışlarıyla telefon trafiğini ve gelmeyen müşteri oranını azaltın.",items:["Randevu teyitleri","SMS/e-posta altyapısı","Durum bildirimleri","Operasyon merkezi"]},
  {no:"06",icon:ShieldCheck,title:"Rol ve güvenlik",lead:"Doğru bilgi, yalnızca doğru ekip üyesine ulaşır.",text:"İşletme sahibi, yönetici ve çalışan rollerini güvenli tenant izolasyonu ve denetlenebilir süreçlerle yönetin.",items:["Rol bazlı erişim","İşletme izolasyonu","KVKK odaklı süreçler","Platform denetimi"]},
];
export default function Page(){return <BusinessPage className="feature-premium"><main><section className="feature-premium-hero"><div><span>ÜRÜNÜN TAMAMI</span><h1>Bir araç seti değil,<br/><em>işletme işletim sistemi.</em></h1><p>Ön masadan müşteri deneyimine, günlük operasyondan büyüme kararlarına kadar her şeyi tek akıcı çalışma alanında birleştirin.</p><div><Link href="/isletmeler/kayit">14 gün ücretsiz başla <ArrowRight size={16}/></Link><Link href="/fiyatlar">Fiyatları gör</Link></div></div><aside><div className="feature-orbit orbit-calendar"><CalendarDays/></div><div className="feature-orbit orbit-users"><UsersRound/></div><div className="feature-orbit orbit-chart"><BarChart3/></div><div className="feature-core"><WandSparkles/><strong>Tek merkez</strong><small>Tüm işletmeniz</small></div></aside></section><section className="feature-premium-list">{features.map(({no,icon:Icon,title,lead,text,items},index)=><article key={title} className={index%2?"reverse":""}><div className="feature-visual"><span>{no}</span><Icon size={42}/><div className="feature-visual-lines">{[1,2,3,4].map(i=><i key={i}/>)}</div></div><div className="feature-copy"><span>{no} · {title.toUpperCase()}</span><h2>{lead}</h2><p>{text}</p><ul>{items.map(item=><li key={item}><Check size={14}/>{item}</li>)}</ul></div></article>)}</section><section className="feature-device-band"><div><Smartphone/><strong>Mobilde</strong><span>Her yerden yönetin</span></div><div><Clock3/><strong>Gerçek zamanlı</strong><span>Her ekran güncel</span></div><div><MessageSquareText/><strong>Bağlantılı</strong><span>Müşteri iletişimi hazır</span></div></section><section className="feature-final"><span>HER ŞEYİ BİRLİKTE DENEYİN</span><h2>İşletmeniz daha akıcı<br/>çalışmaya hazır.</h2><Link href="/isletmeler/kayit">Ücretsiz çalışma alanını aç <ArrowRight size={16}/></Link></section></main></BusinessPage>}
