import { ContentPage } from "@/components/marketing/content-page"; import { createPublicMetadata } from "@/lib/seo/metadata";
export const metadata=createPublicMetadata({title:"Kullanım Koşulları",description:"SeninRandevun hesap, işletme profili, randevu, abonelik, içerik doğruluğu ve platform kullanımına ilişkin güncel hizmet koşulları.",pathname:"/kullanim-kosullari",type:"article"});
export default function Page(){return <ContentPage eyebrow="YASAL · 29 EYLÜL 2026" title="Kullanım koşulları" intro="SeninRandevun'u kullanarak hesap güvenliği, içerik doğruluğu, randevu işlemleri ve yasal kullanıma ilişkin bu koşulları kabul edersiniz." sections={[
{title:"Hizmetin kapsamı",body:"SeninRandevun; işletmelerin profil, hizmet, çalışan, müsaitlik ve randevu süreçlerini yönetmesini; müşterilerin uygun işletme ve saatleri bulup randevu oluşturmasını sağlayan bir teknoloji platformudur. İşletmenin sunduğu asıl hizmetin tarafı veya sağlayıcısı değildir."},
{title:"Hesap ve güvenlik",body:"Kayıt bilgilerinin doğru ve güncel tutulması, giriş ve doğrulama bilgilerinin korunması ve yetkisiz erişimin derhal bildirilmesi kullanıcı sorumluluğundadır. Şüpheli, kötüye kullanıma açık veya mevzuata aykırı hesaplar güvenlik incelemesi süresince sınırlandırılabilir."},
{title:"İşletme içeriği",body:"İşletme adı, yetki, hizmet, fiyat, süre, çalışan, çalışma saati, adres, görsel ve diğer yayınların doğru, güncel, hukuka ve üçüncü taraf haklarına uygun olması işletmenin sorumluluğundadır. Eksik, yanıltıcı, demo veya uygunsuz içerik yayımdan kaldırılabilir."},
{title:"Randevu, iptal ve değişiklik",body:"Randevu işletmenin ilan ettiği müsaitlik ve kurallara göre kurulur. İptal, değişiklik, gecikme, hizmetin kapsamı, fiyatı ve iade gibi hususlar ilgili işletmenin yayımladığı koşullara tabidir. Kullanıcı randevu bilgilerini kontrol etmek ve değişiklikleri zamanında bildirmekle yükümlüdür."},
{title:"Kabul edilebilir kullanım",body:"Hizmet yasa dışı, yanıltıcı, zararlı, taciz edici, otomatik kötüye kullanım oluşturan veya üçüncü taraf haklarını ihlal eden amaçlarla kullanılamaz. Güvenliği aşma, sahte randevu, izinsiz veri toplama, tersine mühendislik ve hizmeti aksatmaya yönelik işlemler yasaktır."},
{title:"Ücretsiz dönem ve abonelik",body:"Lansman kampanyası kapsamında açılan işletme hesapları kayıt tarihinden itibaren ilk 3 ay ücretsizdir. Ücretsiz dönemin sonunda işletme özellikleri güncel plan ve fiyatlandırmaya göre sınırlandırılabilir. Ücretli ödeme akışı devreye alındığında fiyat, yenileme, iptal ve varsa iade koşulları satın alma öncesinde ayrıca gösterilir."},
{title:"Fikri mülkiyet",body:"Platform yazılımı, arayüzü, tasarımı, markası ve özgün içerikleri üzerindeki haklar saklıdır. Kullanıcı içeriklerinin mülkiyeti kullanıcıda kalır; platforma yalnızca hizmeti sunmak ve içeriği kullanıcı talimatına göre göstermek için gerekli sınırlı kullanım yetkisi verilir."},
{title:"Süreklilik ve sorumluluk",body:"Güvenli ve kesintisiz hizmet için makul teknik önlemler alınır; planlı bakım, üçüncü taraf servisleri, internet kesintileri veya mücbir sebepler nedeniyle geçici erişim sorunları yaşanabilir. Emredici hukuk hükümleri saklı kalmak üzere dolaylı zararlar ve işletmenin sunduğu asıl hizmetten doğan uyuşmazlıklar işletme ile müşteri arasındadır."},
{title:"Değişiklik, fesih ve iletişim",body:"Koşullar hizmet veya mevzuat değişikliklerine göre güncellenebilir; esaslı değişiklikler uygun kanallardan duyurulur. Kullanıcı hesabını kapatabilir; yükümlülük ihlalinde erişim askıya alınabilir veya sonlandırılabilir. Sorular için info@seninrandevun.com adresine ulaşabilirsiniz."}
]} cta={false}/>}
