import { ContentPage } from "@/components/marketing/content-page"; import { createPublicMetadata } from "@/lib/seo/metadata";
export const metadata=createPublicMetadata({title:"KVKK Aydınlatma Metni",description:"SeninRandevun kullanıcı, müşteri ve işletme verilerinin işlenmesi, aktarılması, saklanması ve KVKK kapsamındaki haklara ilişkin aydınlatma metni.",pathname:"/kvkk",type:"article"});
export default function Page(){return <ContentPage eyebrow="YASAL · 29 EYLÜL 2026" title="KVKK aydınlatma metni" intro="SeninRandevun kapsamında kişisel verilerin hangi amaçlarla, hangi hukuki sebeplerle ve kimlerle işlendiğini açıklar. Platformdaki işletmeler, kendi müşterilerine ilişkin işlemlerde ayrıca veri sorumlusu olabilir." sections={[
{title:"Veri sorumlusu ve iletişim",body:"SeninRandevun hizmetinin veri sorumlusuna KVKK kapsamındaki başvurularınız için info@seninrandevun.com adresinden ulaşabilirsiniz. Başvurunun kimlik doğrulaması gerektirmesi halinde yalnızca talebin güvenli biçimde sonuçlandırılması için gerekli ek bilgiler istenir.",bullets:["Genel destek: info@seninrandevun.com","Telefon: 0530 478 82 98","İşletme müşterileri, randevu sahibine karşı kendi süreçlerinden ayrıca sorumludur."]},
{title:"İşlenen veri kategorileri",body:"Hizmetin niteliğine göre yalnızca gerekli veriler işlenir.",bullets:["Kimlik ve iletişim: ad-soyad, telefon, e-posta","Hesap ve işletme: profil, yetki, mağaza, hizmet ve çalışan kayıtları","Randevu: seçilen hizmet, çalışan, tarih-saat, işlem durumu ve kullanıcı notu","İşlem güvenliği: oturum, cihaz, IP, doğrulama, hata ve denetim kayıtları","Talep ve destek: mesajlar, başvuru içeriği ve çözüm kayıtları"]},
{title:"Amaçlar ve hukuki sebepler",body:"Veriler; hesabın ve randevunun kurulması veya ifası, güvenliğin sağlanması, taleplerin karşılanması ve mevzuat yükümlülüklerinin yerine getirilmesi için KVKK'nın 5. maddesindeki sözleşmenin kurulması veya ifası, hukuki yükümlülük, hakkın tesisi veya kullanılması ve meşru menfaat sebeplerine dayanılarak işlenir. Açık rıza gerektiren bağımsız bir işlem varsa ayrıca ve isteğe bağlı olarak alınır."},
{title:"Randevu aydınlatması",body:"Randevu oluştururken verilen bilgiler, seçilen işletmeye randevuyu planlayabilmesi ve sizinle randevu hakkında iletişim kurabilmesi için iletilir. Telefon doğrulama kodu yalnızca doğrulama ve güvenlik amacıyla kullanılır; reklam izni anlamına gelmez.",bullets:["Zorunlu alanlar randevunun kurulması ve güvenliği için kullanılır.","İsteğe bağlı notlara sağlık veya diğer özel nitelikli verilerin yazılmaması önerilir.","İptal, değişiklik ve bildirim kayıtları işlem güvenliği için tutulabilir."]},
{title:"Aktarım ve yurt dışı",body:"Veriler; barındırma, kimlik doğrulama, bildirim, e-posta veya SMS ve güvenlik hizmeti sağlayıcılarıyla hizmetin gerektirdiği ölçüde; seçilen işletmeyle randevunun yürütülmesi amacıyla; yetkili kurumlarla ise hukuki zorunluluk halinde paylaşılabilir. Yurt dışına aktarım söz konusu olduğunda KVKK'nın 9. maddesindeki uygun güvenceler uygulanır."},
{title:"Saklama, silme ve güvenlik",body:"Kayıtlar işleme amacı, sözleşme ilişkisi, uyuşmazlık ve mevzuattan doğan saklama yükümlülükleri boyunca tutulur; süre sona erdiğinde silinir, yok edilir veya anonimleştirilir. Yetkilendirme, erişim kaydı, şifreli aktarım, yedekleme ve rol tabanlı erişim gibi tedbirler uygulanır."},
{title:"Haklarınız ve başvuru",body:"KVKK'nın 11. maddesi kapsamında verinizin işlenip işlenmediğini öğrenme, bilgi isteme, amacı ve amaca uygun kullanımı öğrenme, aktarılan kişileri bilme, düzeltme, silme veya yok etme, yapılan işlemlerin alıcılara bildirilmesini isteme, otomatik sonuçlara itiraz ve zarar halinde tazminat talep etme haklarına sahipsiniz.",bullets:["Başvuruda ad-soyad, iletişim bilgisi, talebin konusu ve kimliği doğrulayan bilgiler yer almalıdır.","Başvurular kural olarak en geç 30 gün içinde sonuçlandırılır.","Talebinizi info@seninrandevun.com adresine KVKK Başvurusu konusu ile iletebilirsiniz."]},
{title:"Güncellemeler",body:"Bu metin hizmet, işleme faaliyetleri veya mevzuat değiştiğinde güncellenebilir. Esaslı değişiklikler uygun kanallardan duyurulur; metnin güncel sürümü bu sayfada yayımlanır."}
]} cta={false}/>}
