import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarketingPage } from "@/components/marketing/marketing-shell";
import { LocalBusinessGrid } from "@/components/seo/local-business-grid";
import { LOCAL_CATEGORIES, SITE_URL, businessesForCategory, getFethiyeBusinesses, isLocalCategory, jsonLd } from "@/lib/seo/local-seo";

export const dynamic="force-dynamic";
type Props={params:Promise<{category:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {category}=await params;if(!isLocalCategory(category))return {robots:{index:false,follow:true}};const rows=businessesForCategory(await getFethiyeBusinesses(),category);const item=LOCAL_CATEGORIES[category];const title=`Fethiye ${item.label}leri ve Online Randevu`;const description=`Fethiye'deki ${item.label.toLocaleLowerCase("tr-TR")} işletmelerini keşfet, hizmetleri, fiyatları ve müsait saatleri incele, online randevunu kolayca oluştur.`;const canonical=`/mugla/fethiye/${category}`;return {title,description,alternates:{canonical},robots:{index:rows.length>0,follow:true},openGraph:{title,description,url:`${SITE_URL}${canonical}`,type:"website",images:[item.image]},twitter:{card:"summary_large_image",title,description,images:[item.image]}}}
export default async function FethiyeCategoryPage({params}:Props){const {category}=await params;if(!isLocalCategory(category))notFound();const item=LOCAL_CATEGORIES[category];const rows=businessesForCategory(await getFethiyeBusinesses(),category);const url=`${SITE_URL}/mugla/fethiye/${category}`;const faq=[{q:`Fethiye ${item.label.toLocaleLowerCase("tr-TR")} fiyatlarını görebilir miyim?`,a:"İşletmelerin yayınladığı hizmet süreleri ve fiyatlar mağaza kartlarında ve profil sayfalarında görünür."},{q:"Müsait saatler güncel mi?",a:"Randevu akışı işletmenin çalışma saatleri, ekip uygunluğu ve mevcut randevularına göre anlık hesaplanır."}];const schema={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage",name:`Fethiye ${item.label}leri`,url},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Ana Sayfa",item:SITE_URL},{"@type":"ListItem",position:2,name:"Muğla",item:`${SITE_URL}/mugla`},{"@type":"ListItem",position:3,name:"Fethiye",item:`${SITE_URL}/mugla/fethiye`},{"@type":"ListItem",position:4,name:item.label,item:url}]},...(rows.length>0?[{"@type":"FAQPage",mainEntity:faq.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))}]:[])]};return <MarketingPage><main className="content-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(schema)}}/><nav className="text-xs font-bold text-[#0b6b45]"><Link href="/">Ana Sayfa</Link> / <Link href="/mugla">Muğla</Link> / <Link href="/mugla/fethiye">Fethiye</Link> / {item.label}</nav><section className="mt-8 rounded-[34px] bg-[linear-gradient(135deg,#eff7ec,#dfeee1)] p-8 sm:p-14"><span className="text-[10px] font-black tracking-[.18em] text-[#0b6b45]">FETHİYE · {item.label.toLocaleUpperCase("tr-TR")}</span><h1 className="mt-5 text-5xl font-bold tracking-[-.055em] text-[#10241c] sm:text-7xl">Fethiye {item.label}leri</h1><p className="mt-6 max-w-3xl text-base leading-8 text-[#60756a]">Fethiye&apos;deki gerçek {item.label.toLocaleLowerCase("tr-TR")} işletmelerini, hizmetleri, fiyatları ve uygun randevu saatlerini tek yerde inceleyin.</p></section><section className="py-14"><LocalBusinessGrid businesses={rows}/></section>{rows.length>0&&<section className="space-y-3 pb-16"><h2 className="mb-5 text-3xl font-bold text-[#10241c]">Sık sorulan sorular</h2>{faq.map(x=><details key={x.q} className="rounded-2xl border border-[#153d29]/10 bg-white/75 p-5"><summary className="cursor-pointer font-bold text-[#10241c]">{x.q}</summary><p className="mt-3 text-sm leading-7 text-[#60756a]">{x.a}</p></details>)}</section>}</main></MarketingPage>}
