import { ContentPage } from "@/components/marketing/content-page"; import { createPublicMetadata } from "@/lib/seo/metadata";
export const metadata=createPublicMetadata({title:"Gizlilik Politikası",description:"SeninRandevun web ve mobil hizmetlerinde hangi bilgilerin toplandığını, nasıl kullanıldığını, korunduğunu ve tercihlerinizi nasıl yönetebileceğinizi öğrenin.",pathname:"/gizlilik",type:"article"});
export default function Page(){return <ContentPage eyebrow="YASAL · 29 EYLÜL 2026" title="Gizlilik politikası" intro="SeninRandevun web, iOS ve Android hizmetlerinde bilgilerin nasıl korunduğunu ve tercihlerini nasıl yönetebileceğini sade bir dille açıklar." sections={[
{title:"Kapsam",body:"Bu politika ziyaretçiler, randevu alan müşteriler, işletme sahipleri, işletme çalışanları ve destek kanallarını kullanan kişiler için geçerlidir. İşletmelerin kendi müşteri süreçleri için ek bildirimleri bulunabilir."},
{title:"Toplanan bilgiler",body:"Hesap ve iletişim bilgileri; işletme, hizmet ve çalışan profilleri; randevu ayrıntıları; destek mesajları; cihaz, oturum, IP ve güvenlik kayıtları işlenebilir. Alanlar amaçla sınırlı tutulur ve gereksiz özel nitelikli veri talep edilmez."},
{title:"Bilgileri nasıl kullanıyoruz?",body:"Hesap ve randevu hizmetini sunmak, kimliği ve telefonu doğrulamak, çakışmayı önlemek, bildirim göndermek, dolandırıcılığı engellemek, destek sağlamak ve hukuki yükümlülükleri yerine getirmek için kullanırız. Analitik ve pazarlama teknolojileri yalnızca seçiminizle çalışır."},
{title:"Paylaşım",body:"Randevu bilgileri seçtiğiniz işletmeyle; teknik veriler barındırma, bildirim, SMS veya e-posta, hata izleme ve güvenlik sağlayıcılarıyla amaçla sınırlı olarak paylaşılabilir. Kişisel veriler satılmaz. Yetkili mercilere yalnızca geçerli hukuki yükümlülük halinde açıklama yapılır."},
{title:"Saklama ve güvenlik",body:"Veriler amaç ve yasal yükümlülük sürdüğü kadar tutulur, ardından silinir, yok edilir veya anonimleştirilir. Şifreli aktarım, erişim kontrolü, rol ayrımı, loglama, yedekleme ve düzenli güvenlik kontrolleri uygulanır."},
{title:"Tercihleriniz",body:"Çerez panelinden zorunlu olmayan kategorileri ayrı ayrı açıp kapatabilirsiniz. Bildirim ve hesap tercihlerini ilgili panelden değiştirebilir; KVKK haklarınız için info@seninrandevun.com adresine başvurabilirsiniz."},
{title:"Çocukların gizliliği",body:"Hizmet çocuklara yönelik tasarlanmamıştır. Reşit olmayan bir kişiye ilişkin işlemin veli veya yasal temsilci gözetimi olmadan yapıldığını düşünüyorsanız bizimle iletişime geçin."},
{title:"Değişiklikler ve iletişim",body:"Esaslı politika değişikliklerini uygulama içinden veya uygun iletişim kanallarından duyururuz. Sorular için info@seninrandevun.com adresine yazabilirsiniz."}
]} cta={false}/>}
